// Regenerates public/sitemap.xml from the SEO route manifest.
// Runs at build time, so newly published guides appear automatically —
// no hand-editing of sitemap.xml ever again.

import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';
import { SITE, SITEMAP_ROUTES, absUrl } from '../src/seo/routes.js';

const __dirname = dirname(fileURLToPath(import.meta.url));
const OUT = resolve(__dirname, '../public/sitemap.xml');

const today = new Date().toISOString().slice(0, 10);

const urls = SITEMAP_ROUTES.map((r) => {
  const parts = [
    `    <loc>${absUrl(r.path)}</loc>`,
    `    <lastmod>${r.lastmod || today}</lastmod>`,
    r.changefreq ? `    <changefreq>${r.changefreq}</changefreq>` : null,
    r.priority != null ? `    <priority>${r.priority.toFixed(1)}</priority>` : null,
  ].filter(Boolean);
  return `  <url>\n${parts.join('\n')}\n  </url>`;
}).join('\n');

const xml = `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by scripts/generate-sitemap.mjs — do not edit by hand. -->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urls}
</urlset>
`;

writeFileSync(OUT, xml, 'utf8');
console.log(`[sitemap] wrote ${SITEMAP_ROUTES.length} URLs → ${OUT} (base ${SITE.baseUrl})`);
